# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e9061d49ff0c8550e5e8c822d80f9fc34dcab4602e9110553cfb61582a2d2b4ea4e5ee5f886cbc851d11144b99b8a1298c852ef07e4b83cd0447e8be98fd9b

test:
  secret_key_base: 3697588d1557632f5a652bec0f4917ada6860c3714494fa5ed785fc691d8f87a87baa8245583e690c550ee76889cf4e349a5f001aace460be60e1a64e899e8dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
