---
:consumer_key: kWjeoJtEz5m3rnDVAAYVSQ
:consumer_secret: bgB9B9flvm1hf4gNQyjBZcxzhzXg83ukQP3k3zQUi8o
:oauth_token: 64482503-BuvasksVM7rM6RYuFGxtnba9E8Fm8glDpDcoTR2Ys
:oauth_token_secret: rVC36R3NUUTwh5U6qpzxfKIWBC8uVPVS3f3Or7DWdZc
